<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>J2 Site - {% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="/css/main_5.css">
    <script src="/js/basics_5.js"></script>
  </head>
  <body>
    <!--[if lt IE 10]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div>{% block content %}{% endblock %}</div>
    
    <div class="copyright">
      © Leander Berg<br><br>
      <!-- browser-statistik.de - Welche Browser werden benutzt? -->
        <a href="https://www.browser-statistik.de/benutzer/j2.lulebe.net/" title="Browser Statistiken" target="_blank"><img src="https://www.browser-statistik.de/browser.png?style=2" style="border: 0px;" alt="Browser-Statistiken" /></a><br>
      <!-- browser-statistik.de - Ende -->
      <!-- Begin W3Counter Tracking Code -->
      <script type="text/javascript">
        w3counter(89343);
      </script>
      <noscript>
      <a href="http://www.w3counter.com/stats/89343" target="_blank">
        <img src="https://www.w3counter.com/tracker.php?id=89343" style="border: 0" alt="W3Counter" />
      </a>
      </noscript>
<!-- End W3Counter Tracking Code -->
    </div>
    
    
</body>
</html>
