{% extends "layout.phtml" %}


{% block content %}

<div class="topbar clearfix">
  <h1><a href="{{homelink}}">J2 Seite</a></h1>
  <ul class="left">
    <li><a href="{{profilelink}}">{{username}}</a></li>
    <li id="menuToggle"><a href="#" onclick="toggleMenu(event)">MENÜ</a></li>
  </ul>
  <ul class="right" id="mainmenu">
    {% if student %}
    <li><a href="/app/home.php">Home</a></li>
    {% endif %}
    <li><a href="/app/comments.php">meine Kommentare</a></li>
    <li><a href="/app/students.php">Schüler</a></li>
    <li><a href="/app/classes.php">Kurse</a></li>
    {% if student %}
    <li><a href="/app/teachers.php">Lehrer</a></li>
    <li><a href="/app/misccomments.php">diverses</a></li>
    <li><a href="/app/surveys.php">Umfragen{% if surveys_left %}<b>{{surveys_left}}</b>{% endif %}</a></li>
    {% endif %}
    {% if admin %}
    <li><a href="/app/admin.php" class="admin">Admin-Bereich</a></li>
    {% endif %}
    <li><a href="/index.php?logout=true" class="alert button expand">Logout</a></li>
  </ul>
</div>


<div class="main-container">{% block site %}{% endblock %}</div>

{% endblock %}